// All questions used in the flow.
// Each question has: id, text, hint, type (single|multi|text|select), options
// Conditional: shown only if condition(answers) is true (omit = always show)

export const QUESTIONS = [
  // ── COMPANY BASICS ──────────────────────────────────────────────────
  {
    id: 'company_name',
    section: 'Your company',
    text: 'What is your company name?',
    hint: 'Exactly as registered with the KVK (Chamber of Commerce).',
    type: 'text',
    placeholder: 'e.g. Acme BV',
  },
  {
    id: 'kvk_number',
    section: 'Your company',
    text: 'What is your KVK number?',
    hint: 'This appears in your T&Cs as required by Dutch law.',
    type: 'text',
    placeholder: 'e.g. 12345678',
  },
  {
    id: 'legal_form',
    section: 'Your company',
    text: 'What is your legal form?',
    hint: 'Most Dutch startups are a BV (private limited company).',
    type: 'single',
    options: ['BV (Besloten Vennootschap)', 'Eenmanszaak (Sole trader)', 'VOF (General partnership)', 'NV', 'Stichting (Foundation)', 'Other'],
  },
  {
    id: 'city',
    section: 'Your company',
    text: 'In which city is your registered office?',
    hint: 'Used for the governing law clause — Dutch courts, Dutch law.',
    type: 'text',
    placeholder: 'e.g. Amsterdam',
  },
  {
    id: 'email',
    section: 'Your company',
    text: 'Contact email for legal notices',
    hint: 'Customers will use this to exercise their rights (e.g. data deletion requests).',
    type: 'text',
    placeholder: 'e.g. legal@yourcompany.com',
  },

  // ── BUSINESS TYPE ────────────────────────────────────────────────────
  {
    id: 'business_type',
    section: 'Your business',
    text: 'What kind of business are you?',
    hint: 'This determines which legal frameworks apply to you.',
    type: 'single',
    options: [
      'SaaS / Software product',
      'Marketplace / Platform',
      'E-commerce (physical goods)',
      'Professional services / Consultancy',
      'Mobile app',
      'Data / Analytics product',
      'Fintech / Payments',
      'Healthtech / Medtech',
      'Other',
    ],
  },
  {
    id: 'customer_type',
    section: 'Your business',
    text: 'Who are your customers?',
    hint: 'B2C requires stronger consumer protections (right of withdrawal, stricter T&Cs).',
    type: 'single',
    options: ['Only businesses (B2B)', 'Only consumers (B2C)', 'Both businesses and consumers'],
  },
  {
    id: 'sells_online',
    section: 'Your business',
    text: 'Do customers buy or sign up online?',
    hint: 'Online contracts require specific disclosures under Dutch and EU consumer law.',
    type: 'single',
    options: ['Yes', 'No, sales happen offline / via contracts'],
  },
  {
    id: 'subscription',
    section: 'Your business',
    text: 'Do you offer subscriptions or recurring billing?',
    hint: 'Dutch law requires a specific changes clause and cancellation procedure for ongoing services.',
    type: 'single',
    options: ['Yes', 'No, one-time purchases only'],
  },
  {
    id: 'operates_in_eu',
    section: 'Your business',
    text: 'Do you have customers outside the Netherlands?',
    type: 'single',
    options: ['Netherlands only', 'Elsewhere in the EU', 'Outside the EU too'],
  },

  // ── DATA & PRIVACY ───────────────────────────────────────────────────
  {
    id: 'collects_personal_data',
    section: 'Data & privacy',
    text: 'Do you collect any personal data from users or customers?',
    hint: 'Personal data = anything that can identify a person: name, email, IP address, cookies, etc.',
    type: 'single',
    options: ['Yes', 'No'],
  },
  {
    id: 'data_types',
    section: 'Data & privacy',
    text: 'What types of personal data do you collect?',
    hint: 'Select all that apply. Special category data has stricter rules under GDPR.',
    type: 'multi',
    condition: (a) => a.collects_personal_data === 'Yes',
    options: [
      'Basic contact info (name, email, phone)',
      'Payment / financial data',
      'Location data',
      'Usage / behavioural data (analytics, clickstreams)',
      'Health or medical data',
      'Biometric data (fingerprints, facial recognition)',
      'Political opinions or religious beliefs',
      'Sexual orientation or gender identity',
      'Children\'s data (users under 16)',
      'Employee data',
    ],
  },
  {
    id: 'legal_basis',
    section: 'Data & privacy',
    text: 'On what legal basis do you process this data?',
    hint: 'You must have at least one. Most startups use consent or legitimate interests.',
    type: 'multi',
    condition: (a) => a.collects_personal_data === 'Yes',
    options: [
      'Consent (user ticks a box)',
      'Contract performance (needed to deliver the service)',
      'Legitimate interests (your business reasons)',
      'Legal obligation',
      "Not sure — I'll need guidance",
    ],
  },
  {
    id: 'third_party_processors',
    section: 'Data & privacy',
    text: 'Do you share data with any third-party tools or services?',
    hint: 'e.g. Google Analytics, Stripe, HubSpot, AWS, Mailchimp. These require Data Processing Agreements (DPAs).',
    type: 'single',
    options: ['Yes', 'No'],
  },
  {
    id: 'processors_list',
    section: 'Data & privacy',
    text: 'List the main third-party processors you use',
    hint: 'These will be listed in your privacy policy. Add as many as relevant.',
    type: 'text',
    placeholder: 'e.g. AWS (hosting), Stripe (payments), Google Analytics (analytics)',
    condition: (a) => a.third_party_processors === 'Yes',
  },
  {
    id: 'data_outside_eu',
    section: 'Data & privacy',
    text: 'Is any data stored or processed outside the EU/EEA?',
    hint: 'e.g. US-based services. This requires specific safeguards under GDPR (SCCs or adequacy decisions).',
    type: 'single',
    options: ['Yes', 'No', "I don't know"],
  },
  {
    id: 'uses_cookies',
    section: 'Data & privacy',
    text: 'Do you use cookies or similar tracking technologies?',
    hint: 'Includes analytics pixels, session cookies, marketing trackers.',
    type: 'single',
    options: ['Yes, including analytics/marketing cookies', 'Only strictly necessary cookies', 'No cookies at all'],
  },

  // ── AI & TECHNOLOGY ──────────────────────────────────────────────────
  {
    id: 'uses_ai',
    section: 'AI & technology',
    text: 'Does your product use AI or automated decision-making?',
    hint: 'Includes machine learning models, AI APIs (OpenAI, Claude, etc.), recommendation engines, chatbots.',
    type: 'single',
    options: ['Yes', 'No'],
  },
  {
    id: 'ai_type',
    section: 'AI & technology',
    text: 'What does your AI system do?',
    type: 'multi',
    condition: (a) => a.uses_ai === 'Yes',
    options: [
      'Chatbot / conversational AI visible to users',
      'Automated scoring or ranking of people',
      'Hiring or HR screening',
      'Credit or financial risk assessment',
      'Healthcare or medical decision support',
      'Content recommendation',
      'Fraud detection',
      'Internal tool (not user-facing)',
      'Deepfake or synthetic media generation',
    ],
  },
  {
    id: 'ai_makes_decisions',
    section: 'AI & technology',
    text: 'Does your AI make decisions that significantly affect people?',
    hint: 'e.g. approving a loan, ranking a job applicant, diagnosing a condition. This triggers Article 22 GDPR rights.',
    type: 'single',
    condition: (a) => a.uses_ai === 'Yes',
    options: ['Yes, automatically without human review', 'Yes, but a human always reviews the output', 'No, it only generates content or suggestions'],
  },

  // ── LIABILITY & TERMS ─────────────────────────────────────────────────
  {
    id: 'ip_type',
    section: 'Your IP & liability',
    text: 'What intellectual property does your business have?',
    hint: 'This shapes your IP protection clause.',
    type: 'multi',
    options: [
      'Proprietary software / code',
      'Brand name / trademark',
      'Content (articles, videos, designs)',
      'Database or data sets',
      'Patents or pending patents',
      'None yet',
    ],
  },
  {
    id: 'user_generated_content',
    section: 'Your IP & liability',
    text: 'Can users upload or create content on your platform?',
    hint: 'If yes, you need a content licence clause and a policy for illegal content.',
    type: 'single',
    options: ['Yes', 'No'],
  },
  {
    id: 'liability_cap',
    section: 'Your IP & liability',
    text: 'How do you want to cap your liability?',
    hint: "Dutch law allows liability limitation but you can't fully exclude liability for gross negligence. Under B2C, you can't limit liability for personal injury.",
    type: 'single',
    options: [
      'Cap at the amount paid by the customer in the last 12 months',
      'Cap at a fixed amount (e.g. €500)',
      'No cap — I want to discuss this with a lawyer',
    ],
  },
]

export const SECTIONS = ['Your company', 'Your business', 'Data & privacy', 'AI & technology', 'Your IP & liability']
